### ISSUE TITLE
Could Jakarta EE projects use Eclipse Antenna?

### ISSUE THREAD

**Issue by keilw** [jakartaee/specification-tools#1]
I came across the Eclipse Antenna project: https://projects.eclipse.org/projects/technology.sw360.antenna which aims to document all dependencies of a project and their licenses. Antenna can be used via Maven or Gradle, so it looks easy to use in a build process.

**Comment by edburns** [comment]
Hello @ivargrimstad  can you please add label jea-linked to this issue? I'd like to be able to add labels myself. I have linked it to [AB#91](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/91)

**Comment by ivargrimstad** [comment]
The Antenna project is archived, i.e. not active any longer. If I'm not mistaken, the [Dash License Tool](https://github.com/eclipse/dash-licenses) does the same thing and is the preferred tool to use.
